apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: create-ec2-instance
  title: Create EC2 Instance
  description: A template to create an EC2 instance on AWS using Terraform.
  tags:
    - aws
    - ec2
    - terraform
spec:
  owner: team-a
  type: service
  path: ./template.yaml
